### ISSUE TITLE
The error occurs to require ECMAScript5 and higher

### ISSUE THREAD

**Issue by a-suenami** [typescript-ruby/typescript-node-ruby#3]
@tkawachi

Hi.

I'm use [typescript-rails](https://github.com/funnythingz/typescript-rails) which depend on this repository and [DefinitelyTyped](https://github.com/borisyankov/DefinitelyTyped) for using AngulaJS, then I encounter following error:

```
error TS1056: Accessors are only available when targeting ECMAScript 5 and higher.
```

According to [manual](https://www.npmjs.org/package/typescript-compiler), I should use `--target ES5` option when I compile.

However typescript-node-ruby can’t receive compile options.
Refs.) https://github.com/tkawachi/typescript-node-ruby/blob/master/lib/typescript-node.rb#L19

I think that we can use some compile options, what do you think?

**Comment by wtfiwtz** [comment]
@ClaranMcCann I believe you can use `Typescript::Rails::Compiler.default_options = { }` - only 1.5 years too late :)

**Comment by CiaranMcCann** [comment]
@wtfiwtz indeed you are correct thanks, I found it out with a bit of source code reading

```
self.default_options = [
        "--target", "ES5"
]
```
